#!/usr/bin/env python3
"""Leak-free historical backtest of the ranking method against the given
3-sigma baseline.

Ground truth problem: the challenge gives us no direct label for "this
gateway needed a visit." field_visits.csv only tells us which gateways the
CURRENT (already-biased) process chose to visit -- of which 60.7% found no
fault, so treating "was visited" as ground truth would just reward copying
a process the brief itself says is bad. Instead we use a proxy that is
independent of who chose to look: `meters_read / meters_expected < BAD_RATIO`
for a gateway-week, from meter_read_success.csv, which is generated by the
metering system, not by anyone's gut feel about the network.

That proxy is imperfect too (see REPORT.md, "what this test cannot tell
you" -- a low read ratio can also reflect a meter-side problem unrelated to
gateway health). We report results at multiple thresholds and bootstrap a
confidence interval rather than presenting one number as if it were exact.

meter_read_success.csv stops on 2026-01-26, before the scored window
(2026-02-02 onward) starts -- so this backtest can never leak into the
actual submission, and also can never validate the submission directly.
It validates the METHOD on the weeks we do have ground truth for.
"""

from __future__ import annotations

import pathlib
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from src.io import load_meter_read_success, load_telemetry  # noqa: E402
from src.scoring import blended_scores_for_week, telemetry_flags_for_week  # noqa: E402

COST_WASTED = 380
COST_MISSED = 600
VISITS_PER_WEEK = 15
N_BOOTSTRAP = 5000
RNG_SEED = 0


def run_backtest(data_dir: pathlib.Path, bad_ratios=(0.5, 0.6, 0.7, 0.8)) -> pd.DataFrame:
    telemetry = load_telemetry(data_dir)
    mrs = load_meter_read_success(data_dir)

    candidate_weeks = sorted(
        w for w in mrs["week_start"].unique() if w >= pd.Timestamp("2025-09-08", tz="UTC")
    )

    rows = []
    for wk in candidate_weeks:
        wk_ts = pd.Timestamp(wk)
        sigma_only = telemetry_flags_for_week(telemetry, wk_ts.date())
        blended = blended_scores_for_week(telemetry, mrs, wk_ts.date())
        if sigma_only.empty or blended.empty:
            continue
        top15_sigma = set(sigma_only.sort_values("flagged_hours", ascending=False).head(VISITS_PER_WEEK)["gateway_id"])
        top15_blend = set(blended.head(VISITS_PER_WEEK)["gateway_id"])

        truth_week = mrs[mrs["week_start"] == wk_ts]
        for bad_ratio in bad_ratios:
            bad_gw = set(truth_week.loc[truth_week["read_ratio"] < bad_ratio, "gateway_id"])
            if not bad_gw:
                continue
            sigma_hits = len(top15_sigma & bad_gw)
            blend_hits = len(top15_blend & bad_gw)
            rows.append({
                "week": wk_ts.date().isoformat(),
                "bad_ratio_threshold": bad_ratio,
                "n_bad": len(bad_gw),
                "sigma_hits": sigma_hits,
                "blend_hits": blend_hits,
                "sigma_cost": (VISITS_PER_WEEK - sigma_hits) * COST_WASTED
                + (len(bad_gw) - sigma_hits) * COST_MISSED,
                "blend_cost": (VISITS_PER_WEEK - blend_hits) * COST_WASTED
                + (len(bad_gw) - blend_hits) * COST_MISSED,
            })
    return pd.DataFrame(rows)


def bootstrap_ci(values: np.ndarray, n_boot: int = N_BOOTSTRAP, seed: int = RNG_SEED):
    """Percentile bootstrap 95% CI on the mean, resampling WEEKS with
    replacement -- answers 'how much does this move depending on which
    weeks/gateways we happened to test on,' per the brief's own demand."""
    rng = np.random.default_rng(seed)
    n = len(values)
    means = np.empty(n_boot)
    for i in range(n_boot):
        sample = rng.choice(values, size=n, replace=True)
        means[i] = sample.mean()
    return float(np.percentile(means, 2.5)), float(values.mean()), float(np.percentile(means, 97.5))


def summarize(res: pd.DataFrame, bad_ratio: float) -> None:
    sub = res[res["bad_ratio_threshold"] == bad_ratio]
    n_weeks = sub["week"].nunique()
    saving = (sub["sigma_cost"] - sub["blend_cost"]).to_numpy()
    lo, mid, hi = bootstrap_ci(saving)
    sigma_prec = (sub["sigma_hits"] / VISITS_PER_WEEK).mean()
    blend_prec = (sub["blend_hits"] / VISITS_PER_WEEK).mean()
    print(f"\n-- bad_ratio_threshold = {bad_ratio} ({n_weeks} weeks) --")
    print(f"   precision@15: sigma-only {sigma_prec:.1%}  ->  blended {blend_prec:.1%}")
    print(f"   weekly cost saving (blended vs sigma-only): "
          f"EUR{mid:,.0f}/week  [95% CI {lo:,.0f} to {hi:,.0f}, bootstrapped over weeks]")
    print(f"   total over {n_weeks} backtested weeks: EUR{saving.sum():,.0f}  "
          f"(~EUR{mid*52:,.0f}/year if this held all year, which we do NOT claim it would)")


def main() -> int:
    here = pathlib.Path(__file__).resolve().parent.parent
    data_dir = here / "data"
    res = run_backtest(data_dir)
    res.to_csv(here / "scripts" / "backtest_results.csv", index=False)
    print(f"Backtest written to scripts/backtest_results.csv ({len(res)} week x threshold rows)")
    for br in (0.5, 0.6, 0.7, 0.8):
        summarize(res, br)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
